# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'detailed_editor.ui'
#
# Created: Wed May 01 14:04:04 2019
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DetailedEditor(object):
    def setupUi(self, DetailedEditor):
        DetailedEditor.setObjectName(_fromUtf8("DetailedEditor"))
        DetailedEditor.resize(997, 862)
        DetailedEditor.setMouseTracking(True)
        self.centralwidget = QtGui.QWidget(DetailedEditor)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 140, 351, 131))
        self.groupBox_3.setTitle(_fromUtf8(""))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.rad_fma_anom = QtGui.QRadioButton(self.groupBox_3)
        self.rad_fma_anom.setGeometry(QtCore.QRect(50, 10, 82, 21))
        self.rad_fma_anom.setObjectName(_fromUtf8("rad_fma_anom"))
        self.rad_asset_class_anom = QtGui.QRadioButton(self.groupBox_3)
        self.rad_asset_class_anom.setGeometry(QtCore.QRect(50, 40, 131, 21))
        self.rad_asset_class_anom.setObjectName(_fromUtf8("rad_asset_class_anom"))
        self.rad_resilience_anom = QtGui.QRadioButton(self.groupBox_3)
        self.rad_resilience_anom.setGeometry(QtCore.QRect(50, 70, 121, 21))
        self.rad_resilience_anom.setObjectName(_fromUtf8("rad_resilience_anom"))
        self.rad_any_anom = QtGui.QRadioButton(self.groupBox_3)
        self.rad_any_anom.setGeometry(QtCore.QRect(50, 100, 161, 21))
        self.rad_any_anom.setObjectName(_fromUtf8("rad_any_anom"))
        self.btn_select_anomalies = QtGui.QPushButton(self.groupBox_3)
        self.btn_select_anomalies.setGeometry(QtCore.QRect(260, 90, 66, 31))
        self.btn_select_anomalies.setObjectName(_fromUtf8("btn_select_anomalies"))
        self.tbl_features = QtGui.QTableWidget(self.centralwidget)
        self.tbl_features.setGeometry(QtCore.QRect(20, 320, 951, 401))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbl_features.sizePolicy().hasHeightForWidth())
        self.tbl_features.setSizePolicy(sizePolicy)
        self.tbl_features.setMinimumSize(QtCore.QSize(0, 140))
        self.tbl_features.setMouseTracking(True)
        self.tbl_features.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tbl_features.setColumnCount(9)
        self.tbl_features.setObjectName(_fromUtf8("tbl_features"))
        self.tbl_features.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tbl_features.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_features.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_features.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_features.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_features.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_features.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_features.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_features.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_features.setHorizontalHeaderItem(8, item)
        self.tbl_features.horizontalHeader().setCascadingSectionResizes(True)
        self.tbl_features.horizontalHeader().setDefaultSectionSize(80)
        self.tbl_features.horizontalHeader().setMinimumSectionSize(25)
        self.tbl_features.horizontalHeader().setSortIndicatorShown(True)
        self.tbl_features.horizontalHeader().setStretchLastSection(True)
        self.tbl_features.verticalHeader().setVisible(True)
        self.tbl_features.verticalHeader().setCascadingSectionResizes(False)
        self.tbl_features.verticalHeader().setStretchLastSection(False)
        self.lbl_selection_count = QtGui.QLabel(self.centralwidget)
        self.lbl_selection_count.setGeometry(QtCore.QRect(100, 290, 831, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_selection_count.setFont(font)
        self.lbl_selection_count.setObjectName(_fromUtf8("lbl_selection_count"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(30, 100, 431, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(340, 10, 371, 26))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(105, 55, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.btn_add_layer = QtGui.QPushButton(self.centralwidget)
        self.btn_add_layer.setEnabled(False)
        self.btn_add_layer.setGeometry(QtCore.QRect(660, 50, 231, 31))
        self.btn_add_layer.setObjectName(_fromUtf8("btn_add_layer"))
        self.cbx_postgis_tables = QtGui.QComboBox(self.centralwidget)
        self.cbx_postgis_tables.setGeometry(QtCore.QRect(280, 50, 361, 31))
        self.cbx_postgis_tables.setObjectName(_fromUtf8("cbx_postgis_tables"))
        self.btn_group_edit = QtGui.QPushButton(self.centralwidget)
        self.btn_group_edit.setGeometry(QtCore.QRect(360, 740, 291, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_group_edit.setFont(font)
        self.btn_group_edit.setObjectName(_fromUtf8("btn_group_edit"))
        DetailedEditor.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(DetailedEditor)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 997, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        DetailedEditor.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(DetailedEditor)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        DetailedEditor.setStatusBar(self.statusbar)

        self.retranslateUi(DetailedEditor)
        QtCore.QMetaObject.connectSlotsByName(DetailedEditor)
        DetailedEditor.setTabOrder(self.cbx_postgis_tables, self.btn_add_layer)
        DetailedEditor.setTabOrder(self.btn_add_layer, self.rad_fma_anom)
        DetailedEditor.setTabOrder(self.rad_fma_anom, self.rad_asset_class_anom)
        DetailedEditor.setTabOrder(self.rad_asset_class_anom, self.rad_resilience_anom)
        DetailedEditor.setTabOrder(self.rad_resilience_anom, self.rad_any_anom)
        DetailedEditor.setTabOrder(self.rad_any_anom, self.btn_select_anomalies)
        DetailedEditor.setTabOrder(self.btn_select_anomalies, self.tbl_features)
        DetailedEditor.setTabOrder(self.tbl_features, self.btn_group_edit)

    def retranslateUi(self, DetailedEditor):
        DetailedEditor.setWindowTitle(_translate("DetailedEditor", "Detailed Editor", None))
        self.rad_fma_anom.setText(_translate("DetailedEditor", "fma", None))
        self.rad_asset_class_anom.setText(_translate("DetailedEditor", "asset_class", None))
        self.rad_resilience_anom.setText(_translate("DetailedEditor", "resilience", None))
        self.rad_any_anom.setText(_translate("DetailedEditor", "any of the above", None))
        self.btn_select_anomalies.setText(_translate("DetailedEditor", "OK", None))
        self.tbl_features.setSortingEnabled(True)
        item = self.tbl_features.horizontalHeaderItem(0)
        item.setText(_translate("DetailedEditor", "ID (gid)", None))
        item = self.tbl_features.horizontalHeaderItem(1)
        item.setText(_translate("DetailedEditor", "name", None))
        item = self.tbl_features.horizontalHeaderItem(2)
        item.setText(_translate("DetailedEditor", "fma", None))
        item = self.tbl_features.horizontalHeaderItem(3)
        item.setText(_translate("DetailedEditor", "asset_class", None))
        item = self.tbl_features.horizontalHeaderItem(4)
        item.setText(_translate("DetailedEditor", "resilience", None))
        item = self.tbl_features.horizontalHeaderItem(5)
        item.setText(_translate("DetailedEditor", "Flash", None))
        item = self.tbl_features.horizontalHeaderItem(6)
        item.setText(_translate("DetailedEditor", "Zoom", None))
        item = self.tbl_features.horizontalHeaderItem(7)
        item.setText(_translate("DetailedEditor", "Edit", None))
        item = self.tbl_features.horizontalHeaderItem(8)
        item.setText(_translate("DetailedEditor", "Delete", None))
        self.lbl_selection_count.setText(_translate("DetailedEditor", "selected feature(s)", None))
        self.label_6.setText(_translate("DetailedEditor", "Display rows with invalid values for:", None))
        self.label_2.setText(_translate("DetailedEditor", "RFM Detailed Editing Assistant", None))
        self.label.setText(_translate("DetailedEditor", "Database layer", None))
        self.btn_add_layer.setText(_translate("DetailedEditor", "Add database layer to map", None))
        self.btn_group_edit.setText(_translate("DetailedEditor", "Go to Group Editing", None))

